name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install GCC11, pCap, wxWidgets
      run: sudo apt update && sudo apt install -y gcc-11 g++-11 libpcap-dev libwxgtk3.0-gtk3-dev && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18


    - name: Build
      run: go build sip-ban
