name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pCap
      run: sudo apt update && sudo apt install -y libpcap-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ./dist/sip-ban

    - name: 📂 Sync files
      uses: hocgin/action-qiniu-upload@master
      with:
        access_key: ${{ secrets.QINIU_ACCESS_KEY }}
        secret_key: ${{ secrets.QINIU_SECRET_KEY }}
        bucket: ${{ secrets.QINIU_BUCKET }}
        source_dir: 'dist'
        dest_dir: '/files/sip_ban/'
        ignore_source_map: true
